apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: devlab
  PGADMIN_DEFAULT_EMAIL: admin@devlab.com
  PGADMIN_DEFAULT_PASSWORD: admin123
